apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vllm-ray.fullname" . }}-serve
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vllm-ray.labels" . | nindent 4 }}
  annotations:
    # Force update on content change
    checksum/config: {{ $.Files.Get "files/llm_serve_deepseek.py" | sha256sum }}
    # Add chart version
    helm.sh/chart-version: {{ .Chart.Version }}
data:
  serve.py: |-
{{- $.Files.Get "files/llm_serve_deepseek.py" | nindent 4 }}